export const GET_SPECIFIC_SPACE_CENTER = "GET_SPECIFIC_SPACE_CENTER";
export const SET_SHOW_POP_UP = "SET_SHOW_POP_UP";
export const SET_HOVERED_STATE = "SET_HOVERED_STATE";
export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION";


